Traceback (most recent call last):
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/kawai/anaconda3/envs/jbook/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# plot with various options

g = np.sin(x)

# set the canvas size
plt.figure(figsize=(5,3))

# black solid line with label
plt.plot(x,f,'-k',label=r"$cos(x)$")

# red dashed line with label
plt.plot(x,g,'--r',label=r"$sin(x)$")

plt.xlabel("x")
plt.ylabel("f(x)")

# show the labels as legend
plt.legend(loc=0)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;66;03m# plot with various options[39;00m
[0;32m----> 3[0m g [38;5;241m=[39m np[38;5;241m.[39msin([43mx[49m)
[1;32m      5[0m [38;5;66;03m# set the canvas size[39;00m
[1;32m      6[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m5[39m,[38;5;241m3[39m))

[0;31mNameError[0m: name 'x' is not defined

